import React, { useState, useRef, useEffect } from "react";
import {
  Bot,
  X,
  Send,
  Loader2,
  Clock,
  ExternalLink,
  MessageCircle,
  ChevronRight,
} from "lucide-react";
import axios from "axios";
import ReactMarkdown from "react-markdown";
import PerformanceMetrics from "./PerformanceMetrics";

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:5000/api";

const SUGGESTED_QUESTIONS = [
  "What is the main idea?",
  "Can you explain the hardest part?",
  "What are the three things to remember?",
  "Where does the lecture discuss this most clearly?",
];

function formatTime(seconds) {
  if (seconds == null || isNaN(seconds)) return "??:??";
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
}

/**
 * Builds a YouTube deep-link URL at a specific timestamp.
 * Strips any existing &t= parameter before appending the new one.
 */
function buildTimestampUrl(videoUrl, startTimeSeconds) {
  if (!videoUrl || startTimeSeconds == null) return null;
  const base = videoUrl.replace(/[&?]t=\d+s?/g, "");
  const separator = base.includes("?") ? "&" : "?";
  return `${base}${separator}t=${Math.floor(startTimeSeconds)}s`;
}

/**
 * SourceCard — displays a retrieved transcript chunk with its timestamp and a
 * clickable link to the exact moment in the YouTube video.
 * Timestamps come directly from ChromaDB metadata (not generated by the LLM).
 */
function SourceCard({ source, videoUrl, index }) {
  const timestampUrl = buildTimestampUrl(videoUrl, source.startTime);
  const snippet = source.text?.trim().slice(0, 120);
  const isSnippetTruncated = source.text?.length > 120;

  return (
    <div className="mt-2.5 rounded-lg bg-slate-900/40 border border-slate-800/80 hover:border-purple-500/30 transition-all duration-200 group overflow-hidden shadow-sm">
      {/* Timestamp row */}
      <div className="flex items-center justify-between px-3 py-1.5 border-b border-slate-800/50 bg-slate-950/30">
        <span className="flex items-center gap-1.5 text-xs font-mono font-semibold text-blue-400">
          <Clock className="w-3 h-3 shrink-0" />
          {formatTime(source.startTime)} – {formatTime(source.endTime)}
        </span>

        {timestampUrl && (
          <a
            href={timestampUrl}
            target="_blank"
            rel="noreferrer"
            title="Watch this moment in the video"
            className="flex items-center gap-1 text-[10px] font-bold text-slate-400 hover:text-purple-400 transition-colors bg-slate-900 px-2 py-0.5 rounded border border-slate-800"
          >
            Watch <ExternalLink className="w-2.5 h-2.5" />
          </a>
        )}
      </div>

      {/* Snippet */}
      <p className="px-3 py-2 text-[11px] text-slate-450 leading-relaxed italic line-clamp-2">
        "{snippet}
        {isSnippetTruncated ? "…" : ""}"
      </p>
    </div>
  );
}

function ChatMessage({ msg, videoUrl }) {
  const isUser = msg.role === "user";

  return (
    <div
      className={`flex flex-col ${isUser ? "items-end" : "items-start"} mb-5 animate-fade-in`}
    >
      {isUser ? (
        <div className="max-w-[90%] px-4 py-2.5 bg-blue-600/20 border border-blue-700/30 rounded-2xl rounded-tr-sm text-sm text-blue-100 leading-relaxed shadow-sm">
          {msg.content}
        </div>
      ) : (
        <div className="w-full">
          {/* AI label */}
          <div className="flex items-center gap-2 mb-2">
            <div className="w-6 h-6 rounded-full bg-purple-600/20 border border-purple-500/30 flex items-center justify-center text-purple-400 shrink-0 shadow-sm">
              <Bot className="w-3.5 h-3.5" />
            </div>
            <span className="text-xs font-semibold text-purple-400">Tutor</span>
          </div>

          {/* Answer text rendered as Markdown */}
          <div className="text-sm text-slate-300 leading-relaxed space-y-2">
            <ReactMarkdown
              components={{
                p: ({ children }) => (
                  <p className="mb-2 last:mb-0 leading-relaxed text-slate-300">
                    {children}
                  </p>
                ),
                ul: ({ children }) => (
                  <ul className="list-disc pl-5 mb-2 space-y-1.5">
                    {children}
                  </ul>
                ),
                ol: ({ children }) => (
                  <ol className="list-decimal pl-5 mb-2 space-y-1.5">
                    {children}
                  </ol>
                ),
                li: ({ children }) => (
                  <li className="text-slate-300 leading-relaxed">{children}</li>
                ),
                strong: ({ children }) => (
                  <strong className="font-bold text-slate-100">
                    {children}
                  </strong>
                ),
                em: ({ children }) => (
                  <em className="italic text-slate-200">{children}</em>
                ),
                code: ({ className, children, ...props }) => {
                  const inline = !className;
                  return inline ? (
                    <code
                      className="bg-slate-900 border border-slate-800 px-1 py-0.5 rounded text-purple-300 font-mono text-xs"
                      {...props}
                    >
                      {children}
                    </code>
                  ) : (
                    <pre className="bg-slate-950 border border-slate-900/60 p-3 rounded-lg overflow-x-auto my-2.5 shadow-inner">
                      <code
                        className={`${className} text-slate-250 font-mono text-xs block`}
                        {...props}
                      >
                        {children}
                      </code>
                    </pre>
                  );
                },
                h1: ({ children }) => (
                  <h1 className="text-base font-bold text-slate-200 mt-4 mb-2 border-b border-slate-800/40 pb-1">
                    {children}
                  </h1>
                ),
                h2: ({ children }) => (
                  <h2 className="text-sm font-bold text-slate-200 mt-4 mb-2">
                    {children}
                  </h2>
                ),
                h3: ({ children }) => (
                  <h3 className="text-xs font-bold text-slate-350 mt-3 mb-1.5">
                    {children}
                  </h3>
                ),
              }}
            >
              {msg.content}
            </ReactMarkdown>
          </div>

          {/* Sources from transcript — clearly separated */}
          {msg.sources && msg.sources.length > 0 && (
            <div className="mt-5 pt-4 border-t border-slate-800/40">
              <p className="text-[10px] font-bold uppercase tracking-wider text-purple-400 mb-2 flex items-center gap-1.5">
                <ChevronRight className="w-3.5 h-3.5" />
                From the transcript
              </p>
              <div className="space-y-1">
                {msg.sources.map((s, i) => (
                  <SourceCard
                    key={i}
                    source={s}
                    videoUrl={videoUrl}
                    index={i}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Collapsible latency metrics */}
          {msg.latency && <PerformanceMetrics latency={msg.latency} />}
        </div>
      )}
    </div>
  );
}

function AITutor({
  videoId,
  videoUrl,
  isOpen,
  onClose,
  onOpen,
  initialQuestion,
}) {
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef(null);

  // Track which initialQuestion value we've already handled to avoid double-firing.
  // useEffect dependencies can fire twice in StrictMode or on prop re-renders.
  const consumedInitialQuestionRef = useRef(null);

  // Auto-scroll to the bottom whenever messages or loading state changes
  useEffect(() => {
    if (bottomRef.current) {
      bottomRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages, loading]);

  // Handle an initialQuestion sent from an external source (e.g. quiz "Ask AI Tutor")
  useEffect(() => {
    if (
      initialQuestion &&
      videoId &&
      initialQuestion !== consumedInitialQuestionRef.current
    ) {
      consumedInitialQuestionRef.current = initialQuestion;
      sendMessage(initialQuestion);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialQuestion, videoId]);

  const sendMessage = async (questionText) => {
    const q = questionText || input.trim();
    if (!q || !videoId || loading) return;

    const userMsg = { role: "user", content: q };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const res = await axios.post(`${API_BASE_URL}/videos/${videoId}/chat`, {
        question: q,
      });
      const assistantMsg = {
        role: "assistant",
        content: res.data.answer,
        sources: res.data.sources || [],
        latency: res.data.latency,
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } catch (err) {
      const errMsg =
        err.response?.data?.error ||
        "Something went wrong. Please check the backend connection.";
      setMessages((prev) => [
        ...prev,
        { role: "assistant", content: errMsg, sources: [] },
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  return (
    <>
      {/* Mobile toggle button */}
      <button
        onClick={onOpen}
        aria-label="Open Tutor"
        className={`fixed bottom-6 right-6 z-50 lg:hidden flex items-center gap-2 px-4 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold rounded-xl shadow-2xl shadow-blue-500/30 transition-all ${isOpen ? "opacity-0 pointer-events-none" : "opacity-100"}`}
      >
        <Bot className="w-5 h-5" />
        Tutor
      </button>

      {/* Mobile backdrop overlay */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/60 z-40 lg:hidden backdrop-blur-sm"
          onClick={onClose}
          aria-hidden="true"
        />
      )}

      {/* Sidebar / Drawer panel */}
      <div
        className={`
          fixed lg:sticky top-0 right-0 h-screen z-50 flex flex-col
          w-[90vw] sm:w-96 lg:w-auto lg:h-[calc(100vh-2rem)] lg:max-h-[900px]
          glass-panel-glow border-l border-slate-800/80 rounded-l-2xl lg:rounded-2xl
          transition-transform duration-300 ease-in-out
          ${isOpen ? "translate-x-0" : "translate-x-full lg:translate-x-0"}
          overflow-hidden shadow-2xl
        `}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-800/60 bg-slate-950/50 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-purple-600/20 border border-purple-500/30 text-purple-400 flex items-center justify-center">
              <Bot className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-slate-100">Tutor</h2>
              <p className="text-[10px] text-slate-500">
                Based on this transcript
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close Tutor"
            className="text-slate-500 hover:text-slate-200 transition-colors p-1 rounded-md hover:bg-slate-800 lg:hidden"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Messages area */}
        <div className="flex-grow overflow-y-auto p-4">
          {/* Empty state with suggested questions */}
          {messages.length === 0 && !loading && (
            <div className="text-center pt-6 animate-fade-in">
              <div className="w-12 h-12 rounded-full bg-purple-600/10 border border-purple-500/20 flex items-center justify-center mx-auto mb-3">
                <MessageCircle className="w-6 h-6 text-purple-400" />
              </div>
              <p className="text-sm font-medium text-slate-300 mb-1">
                Ask anything about this lecture
              </p>
              <p className="text-xs text-slate-500 mb-6">
                Ask about anything covered in the lecture.
              </p>

              <div className="space-y-2">
                {SUGGESTED_QUESTIONS.map((q, i) => (
                  <button
                    key={i}
                    onClick={() => sendMessage(q)}
                    disabled={loading}
                    className="w-full text-left text-xs p-3 rounded-lg bg-slate-900/60 border border-slate-800/70 hover:border-purple-800/40 hover:bg-slate-900 text-slate-400 hover:text-slate-200 transition-all disabled:opacity-50"
                  >
                    {q}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Message history */}
          {messages.map((msg, i) => (
            <ChatMessage key={i} msg={msg} videoUrl={videoUrl} />
          ))}

          {/* Loading indicator */}
          {loading && (
            <div className="flex items-center gap-3 text-slate-500 mb-4">
              <div className="w-6 h-6 rounded-full bg-purple-600/20 border border-purple-500/30 flex items-center justify-center shrink-0">
                <Loader2 className="w-3.5 h-3.5 text-purple-400 animate-spin" />
              </div>
              <span className="text-xs animate-pulse">
                Looking through the lecture…
              </span>
            </div>
          )}

          <div ref={bottomRef} />
        </div>

        {/* Input area */}
        <div className="p-3 border-t border-slate-800/60 bg-slate-950/50 shrink-0">
          <div className="relative flex items-center gap-2">
            <input
              type="text"
              id="ai-tutor-input"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Ask a question about the lecture..."
              disabled={loading || !videoId}
              className="flex-grow text-sm bg-slate-900/80 border border-slate-800 focus:border-purple-500/60 focus:ring-1 focus:ring-purple-500/20 rounded-lg px-4 py-2.5 text-slate-200 placeholder-slate-600 outline-none transition-all"
            />
            <button
              id="ai-tutor-send"
              onClick={() => sendMessage()}
              disabled={loading || !input.trim() || !videoId}
              aria-label="Send question"
              className="w-10 h-10 flex items-center justify-center bg-purple-600 hover:bg-purple-500 disabled:bg-slate-800 disabled:text-slate-600 text-white rounded-lg transition-all shrink-0"
            >
              <Send className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

export default AITutor;
