const { generateEmbeddings } = require('./embedding.service');
const { searchChunks } = require('../clients/chroma.client');
const { generateChatResponse } = require('./llm.service');

// Configurable via environment variable so it can be tuned against the
// evaluation dataset without touching application code.
const RAG_DISTANCE_THRESHOLD = Number(process.env.RAG_DISTANCE_THRESHOLD ?? 1.5);

async function handleChat(videoId, question, videoSummary) {
  try {
    const totalStart = Date.now();

    // 1. Embed the query
    const embedStart = Date.now();
    const queryEmbeddings = await generateEmbeddings([question]);
    const queryEmbedding = queryEmbeddings[0];
    const embedLatency = Date.now() - embedStart;

    // 2. Vector similarity search — scoped to this videoId
    const retrieveStart = Date.now();
    const topChunks = await searchChunks(videoId, queryEmbedding, 5);
    const retrieveLatency = Date.now() - retrieveStart;

    // 3. Relevance threshold — discard chunks above the distance threshold.
    const relevantChunks = topChunks.filter(chunk => chunk.distance < RAG_DISTANCE_THRESHOLD);

    // Observability: log each stage count so retrieval issues are immediately
    // diagnosable without instrumenting the LLM response.
    console.log(
      `[RAG] videoId=${videoId} | ` +
      `chroma_returned=${topChunks.length} | ` +
      `after_isolation=${topChunks.length} | ` +  // isolation guard already applied inside searchChunks
      `after_relevance=${relevantChunks.length} | ` +
      `threshold=${RAG_DISTANCE_THRESHOLD} | ` +
      `sending_to_llm=${relevantChunks.length}`
    );

    if (relevantChunks.length === 0) {
      return {
        answer: "I couldn't find enough relevant information in this video to answer that. Try asking about a topic that's covered in the lecture.",
        sources: [],
        latency: {
          embedding: embedLatency,
          retrieval: retrieveLatency,
          generation: 0,
          total: Date.now() - totalStart,
        },
      };
    }

    // 4. Generate grounded LLM response from retrieved context
    const llmResult = await generateChatResponse(question, relevantChunks, videoSummary);

    // 5. Format sources — timestamps are derived from ChromaDB metadata,
    //    NOT generated by the LLM. This makes citations deterministic and reliable.
    const sources = relevantChunks.map(chunk => ({
      text: chunk.text,
      startTime: chunk.startTime,
      endTime: chunk.endTime,
    }));

    const totalLatency = Date.now() - totalStart;

    return {
      answer: llmResult.content,
      sources,
      latency: {
        embedding: embedLatency,
        retrieval: retrieveLatency,
        generation: llmResult.latency,
        total: totalLatency,
      },
    };
  } catch (error) {
    console.error('[RAG] Pipeline error:', error.message);
    throw error;
  }
}

module.exports = {
  handleChat,
};
